### ISSUE TITLE
http code 422 when StatusCode is an int

### ISSUE THREAD

**Issue by timothyclarke** [jacobbednarz/go-csp-collector#15]
With Google Chrome	70.0.3538.77 (Official Build) (64-bit), chrome is sending the `status-code` unquoted which is then interpreted as an int rather than a string. 

eg  (bad)
```
curl -vvv -H 'Content-Type: application/csp-report;charset=utf-8' --data '{"csp-report":{"document-uri":"https://example.com/foo/bar","referrer":"https://www.google.com/","violated-directive":"default-src self","original-policy":"default-src self; report-uri /csp-hotline.php","blocked-uri":"http://evilhackerscripts.com", "status-code": 0 }}' http://localhost:8080
```
If `status-code` is either omitted, or the value is quoted then things work fine.

I only noticed this after I upgraded from an earlier version of chrome.

**Comment by jacobbednarz** [comment]
I just double checked this against CSP2 and CSP3 and both define it as a
long or int. I just missed it 🤦‍♂️

Happy if you want to PR this change, or I can do it tomorrow.

**Comment by timothyclarke** [comment]
Some browsers are still quoting it which would then be a string not an int.
I don't think my go is good enough to normalize both string and int.

I'm happy for this to wait.

**Comment by jacobbednarz** [comment]
No problems at all @timothyclarke. #16 should address this and just in case you're interested, accepting multiple values can be done by using an [empty interface](https://tour.golang.org/methods/14). The smallest possible diff here is:

```diff 
- StatusCode         string `json:"status-code"`
+ StatusCode         interface{} `json:"status-code"`
```

The PR I've put up also splits out the nested struct since they are a real pain to use as literals (which makes the diff a touch bigger). The rest is test case related 😄 Hope this explains things!
